export type TeamMember = {
  image: string;
  name: string;
  title: string;
  program: string;
  year: string;
  email?: string;
  linkedin?: string;
};

export const teamData: TeamMember[] = [
  {
    image: '/team/alppppp.jpeg',
    name: 'Alp Unsal',
    title: 'Co-President',
    program: 'CS & Ivey HBA',
    year: '3rd Year',
    email: 'aunsal3@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/alpunsal/',
  },
  {
    image: '/team/taylorr.jpeg',
    name: 'Taylor McCloskey',
    title: 'Co-President',
    program: 'MIT',
    year: '4th year',
    email: 'tmcclos2@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/taylor-mccloskey-77950918a/',
  },
  {
    image: '/team/erin.jpeg',
    name: 'Erin Hu',
    title: 'Co-VP Operations',
    program: 'Urban Development',
    year: '4th year',
    email: 'ehu24@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/huerin/',
  },
  {
    image: '/team/aiden.jpeg',
    name: 'Aiden Shin',
    title: 'Co-VP Operations',
    program: 'Economics',
    year: '3rd year',
    email: 'ashin25@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/aidenshin/',
  },
  {
    image: '/team/joann2.png',
    name: 'Joann R.',
    title: 'VP Operational Strategy & Execution',
    program: 'CS & MIT',
    year: '3rd year',
    email: 'jranjit@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/joannmr/',
  },
  {
    image: '/team/mia.jpeg',
    name: 'Mia Mcdonalds',
    title: 'VP Internal Affairs & Director of AI',
    program: 'Engineering',
    year: '3rd year',
    email: 'mmacd367@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/mia-s-macdonald/',
  },
  {
    image: '/team/megan.jpeg',
    name: 'Megan Kingston',
    title: 'VP Brand Strategy',
    program: 'MIT',
    year: '3rd year',
    email: 'mkingst9@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/megan-kingston-/',
  },
  {
    image: '/team/adam.jpeg',
    name: 'Adam Seaton',
    title: 'VP Student Innovation Projects',
    program: 'Computer Science',
    year: '3rd year',
    email: 'aseaton3@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/adam-seaton-855440262/',
  },
  {
    image: '/team/isabel.jpeg',
    name: 'Isabel Ke',
    title: 'VP Finance',
    program: 'Computer Science',
    year: '2nd year',
    email: 'ike@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/isabel-ke/',
  },
  {
    image: '/team/sabina.jpeg',
    name: 'Sabina Radhi',
    title: 'VP Communications',
    program: 'Computer Science',
    year: '3rd year',
    email: 'sradhi@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/sabina-radhi-28b590293/',
  },
  {
    image: '/team/vaanya.jpeg',
    name: 'Vaanya Puri',
    title: 'VP Artificial Intelligence',
    program: 'Computer Science',
    year: '3rd year',
    email: 'vpuri22@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/vaanyap/',
  },



  {
    image: '/team/maya.jpeg',
    name: 'Maya Umicevic',
    title: 'VP IBM',
    program: 'BMOS (Finance)',
    year: 'HBA',
    email: 'mumicevi@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/maya-umicevic-3117aa233/',
  },
  {
    image: '/team/justin.jpeg',
    name: 'Justin Dhillon',
    title: 'VP IBM',
    program: 'Computer Science',
    year: '2nd year',
    email: 'jdhill94@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/justinsinghdhillon/',
  },
  {
    image: '/team/fahmid.jpeg',
    name: 'Fahmid Abdullah',
    title: 'VP Digital Transformation & Technology',
    program: 'Computer Science',
    year: '4th year',
    email: 'fabdull9@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/fahmid-abdullah/',
  },
  {
    image: '/team/asad2.jpeg',
    name: 'Asad Awawdeh',
    title: 'Director of Visual Creatives',
    program: 'Criminology & Political Science',
    year: '4th year',
    email: 'aawawdeh@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/asadawawdeh/',
  },
  {
    image: '/team/henry.jpeg',
    name: 'Henry Wang',
    title: 'Co-Director of AI',
    program: 'Software Engineering',
    year: '3rd year',
    email: 'hwan577@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/henry-wang-131b162aa/',
  },
  {
    image: '/team/richard.jpeg',
    name: 'Richard Augustine',
    title: 'Co-Director of AI',
    program: 'Mechatronics',
    year: '3rd year',
    email: 'raugust3@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/richard-augustine/',
  },
  {
    image: '/team/ethan.jpeg',
    name: 'Ethan Carvalho',
    title: 'Director of AI',
    program: 'CS & Economics',
    year: '3rd year',
    email: 'ecarval4@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/ethan-carvalho/',
  },
  {
    image: '/team/nathan.jpeg',
    name: 'Nathan Wan',
    title: 'Director of AI',
    program: 'Engineering',
    year: '2nd year',
    email: 'nwan23@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/nathan-wan-82355b258/',
  },
  {
    image: '/team/rishabh.jpeg',
    name: 'Rishabh Jain',
    title: 'Director of Cybersecurity',
    program: 'Computer Science',
    year: 'Graduate',
    email: 'rjain57@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/1rishabhjain/',
  },
  {
    image: '/team/henrique.jpeg',
    name: 'Henrique Leite',
    title: 'Director of Cybersecurity',
    program: 'Computer Science',
    year: '2nd year',
    email: 'hleite@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/henrique-leite-3251a4209/',
  },
  {
    image: '/team/kalpi.jpeg',
    name: 'Kalpi Patel',
    title: 'Director of Cybersecurity',
    program: 'Computer Science',
    year: '3rd year',
    email: 'kpate629@uwo.ca',
    linkedin: 'https://www.linkedin.com/in/kalpipatel/',
  },
];